# Generated by Django 5.2.4 on 2025-08-03 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('received_text', models.TextField()),
                ('language', models.CharField(default='en', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CorrectedWord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('incorrect_word', models.CharField(max_length=30)),
                ('corrected_word', models.CharField(max_length=30)),
                ('query_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.correctionrequest')),
            ],
        ),
        migrations.AddField(
            model_name='correctionrequest',
            name='session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.session'),
        ),
        migrations.AddField(
            model_name='session',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.CreateModel(
            name='WordFeedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('accepted', models.BooleanField()),
                ('feedback', models.CharField(max_length=200)),
                ('word_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.correctedword')),
            ],
        ),
    ]
