# Generated by Django 5.2.5 on 2025-08-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctionrequest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
