# Generated by Django 5.2.5 on 2025-08-31 05:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_session_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correctionrequest',
            options={'permissions': [('create_correction_request', 'Can store user text in database')]},
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
