# Generated by Django 5.2.5 on 2025-09-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_correctionrequest_options_user_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='correctionrequest',
            name='session_id',
            field=models.CharField(max_length=40),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
