# Generated by Django 5.2.6 on 2025-10-01 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_usersession"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersession",
            name="session",
        ),
        migrations.RemoveField(
            model_name="usersession",
            name="user",
        ),

        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="correctionrequest",
                    name="user",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            database_operations=[],
        ),

        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="correctionrequest",
                    name="word_count",
                    field=models.IntegerField(default=0),
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name="correctedword",
            name="query_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="corrected_words",
                to="api.correctionrequest",
            ),
        ),
        migrations.AddIndex(
            model_name="correctionrequest",
            index=models.Index(
                fields=["user", "created_at"], name="api_correct_user_id_681d49_idx"
            ),
        ),
        migrations.DeleteModel(
            name="UserSession",
        ),
    ]
